from enum import Enum

class MessageTopics(Enum):
  USER_GREETING = "user-greetings"
  AI_INTRODUCTION = "ai-introduction"
  LOOKING_FOR_PARTNER = "looking-for-partner"
  HOBBIES_MOVIES = "hobbies-movies"
  DISLIKE_MOVIES = "dislike-movies"
  HOBBIES_EXERCISE = "hobbies-exercise"
  DISLIKE_EXERCISE = "dislike-exercise"
  HOBBIES_ART = "hobbies-art"
  DISLIKE_ART = "dislike-art"
  HOBBIES_TECHNOLOGY = "hobbies-technology"
  DISLIKE_TECHNOLOGY = "dislike-technology"
  HOBBIES_CAREER = "hobbies-career"
  DISLIKE_CAREER = "dislike-career"
  HOBBIES_COFFEE = "hobbies-coffeee"
  DISLIKE_COFFEE = "dislike-coffeee"
  HOBBIES_MUSIC = "hobbies-music"
  DISLIKE_MUSIC = "dislike-music"
  HOBBIES_BOOKS = "hobbies-books"
  DISLIKE_BOOKS = "dislike-books"
  HOBBIES_PET = "hobbies-pet"
  DISLIKE_PET = "dislike-pet"
  HOBBIES_TRAVELING = "hobbies-traveling"
  DISLIKE_TRAVELING = "dislike-traveling"
  HOBBIES_PHOTOGRAPHY = "hobbies-photography"
  DISLIKE_PHOTOGRAPHY = "dislike-photography"
  HOBBIES_WRITING = "hobbies-writing"
  DISLIKE_WRITING = "dislike-writing"
  HOBBIES_DANCE = "hobbies-dance"
  DISLIKE_DANCE = "dislike-dance"
  HOBBIES_GAMING = "hobbies-gaming"
  DISLIKE_GAMING = "dislike-gaming"
  HOBBIES_COOKING = "hobbies-cooking"
  DISLIKE_COOKING = "dislike-cooking"
  HOBBIES_GARDENING = "hobbies-yoga"
  DISLIKE_GARDENING = "dislike-yoga"